# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import hello_pb2 as proto_dot_hello__pb2


class HelloWordStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Hello = channel.unary_unary(
        '/HelloWord/Hello',
        request_serializer=proto_dot_hello__pb2.StringRequest.SerializeToString,
        response_deserializer=proto_dot_hello__pb2.StringResponse.FromString,
        )


class HelloWordServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Hello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloWordServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Hello': grpc.unary_unary_rpc_method_handler(
          servicer.Hello,
          request_deserializer=proto_dot_hello__pb2.StringRequest.FromString,
          response_serializer=proto_dot_hello__pb2.StringResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'HelloWord', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
